github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addCheck: true

tasks:
  - init: |
      echo "NODE_ENV=development" > .env
      echo "PORT=3000" >> .env
      echo "REACT_APP_SERVER_API=https://mp-server-staging.vaulthill.io/graphql" >> .env
      npm install && npm run build
      command: npm run start

ports:
  - port: 3000
    onOpen: ignore
    visibility: public

    
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - github.vscode-pull-request-github
    - bradlc.vscode-tailwindcss
