export { default as vlandid } from './images/icons/vlandid.svg'
export { default as xycordinate } from './images/icons/xycordinate.svg'
export { default as cluster } from './images/icons/cluster.svg'
export { default as district } from './images/icons/district.svg'
export { default as island } from './images/icons/island.svg'
export { default as typology } from './images/icons/typology.svg'
